export const UPDATE_CURRENT_POSITION = "UPDATE_CURRENT_POSITION";
export const UPDATE_RADIUS = "UPDATE_RADIUS";
export const UPDATE_CIRCONSCRIPTION = "UPDATE_CIRCONSCRIPTION";
export const UPDATE_DEPARTEMENT = "UPDATE_DEPARTEMENT";
export const UPDATE_OPTIMIZED_PATH = "UPDATE_OPTIMIZED_PATH";
export const UPDATE_REFRESH_POINTS = "UPDATE_REFRESH_POINTS";
