export const SET_CURRENT_POSITION = "SET_CURRENT_POSITION";
export const SET_RADIUS = "SET_RADIUS";
export const SET_CIRCONSCRIPTION = "SET_CIRCONSCRIPTION";
export const SET_DEPARTEMENT = "SET_DEPARTEMENT";
export const SET_OPTIMIZED_PATH = "SET_OPTIMIZED_PATH";
export const SET_REFRESH_POINTS = "SET_REFRESH_POINTS";